"""check received coupons

Revision ID: 4145710159a3
Revises: 5456dc6eedd1
Create Date: 2021-08-13 23:26:06.249016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4145710159a3'
down_revision = '5456dc6eedd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('received_coupons', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'received_coupons')
    # ### end Alembic commands ###
