"""coupons field

Revision ID: f03864302232
Revises: ededb13a515d
Create Date: 2021-08-11 14:36:03.996735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03864302232'
down_revision = 'ededb13a515d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coupons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coupons')
    # ### end Alembic commands ###
